// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwfxJ5-vaYHQWeb-hrmskBIEssJVa9aQg',
    appId: '1:746657984736:web:78b024ea8fa7181f302085',
    messagingSenderId: '746657984736',
    projectId: 'crediscotia-fuerzaventas',
    authDomain: 'crediscotia-fuerzaventas.firebaseapp.com',
    storageBucket: 'crediscotia-fuerzaventas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu9gEinsylPeps9ugHFpv5mp0mcdulWq8',
    appId: '1:746657984736:android:e75d8f03a536aff9302085',
    messagingSenderId: '746657984736',
    projectId: 'crediscotia-fuerzaventas',
    storageBucket: 'crediscotia-fuerzaventas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzljKubhLSQa_2pNFefyssGWPySY4_ztg',
    appId: '1:746657984736:ios:bf8395af7eefc8df302085',
    messagingSenderId: '746657984736',
    projectId: 'crediscotia-fuerzaventas',
    storageBucket: 'crediscotia-fuerzaventas.firebasestorage.app',
    iosBundleId: 'com.example.semana5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzljKubhLSQa_2pNFefyssGWPySY4_ztg',
    appId: '1:746657984736:ios:bf8395af7eefc8df302085',
    messagingSenderId: '746657984736',
    projectId: 'crediscotia-fuerzaventas',
    storageBucket: 'crediscotia-fuerzaventas.firebasestorage.app',
    iosBundleId: 'com.example.semana5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwfxJ5-vaYHQWeb-hrmskBIEssJVa9aQg',
    appId: '1:746657984736:web:10853fd10d954c2c302085',
    messagingSenderId: '746657984736',
    projectId: 'crediscotia-fuerzaventas',
    authDomain: 'crediscotia-fuerzaventas.firebaseapp.com',
    storageBucket: 'crediscotia-fuerzaventas.firebasestorage.app',
  );

}